### ISSUE TITLE
Manufactured solution test

### ISSUE THREAD

**Issue by Sidaty1** [mimesis-inria/caribou#116]
We would like to validate the HyperelasticForceField_FeniCS on a manufactured solution

**Comment by Ziemnono** [comment]
Works for linear tetrahedron using SaintVenantKirchhoff, a bit of work has still to be done for quadratic tetrahedron (difference due to index changes)

**Comment by Ziemnono** [comment]
Last results for the quadratic tetrahedron
```
SOFA relative L2 error at 100% load: 9.582959168931972e-06
FEniCS relative L2 error at 100% load: 9.582959166061108e-06
Difference in relative L2 error at 100% load: 2.8708640147220507e-15
```
Seems good enough for me :)
